title: Yizheng's Blog
author: Yizheng Huang
email: huangyz0918@gmail.com
description: Hard work always pays off.
url: "http://blog.huangyz.name/" 

# Build settings
theme: moving
plugins:
  - jekyll-feed

moving:
  date_format: "%b %d"
  back_to: "Index"
