title: Yizheng's Blog
author: Yizheng Huang
email: huangyz0918@gmail.com
description: Hard work always pays off.
url: "http://blog.huangyz.name/" 

# Build settings
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed

moving:
  back_to: "Index"
