title: 一脸傲娇的喵呜喵
author: Liang Guo
email: guolg@cn.ibm.com
description: Connect the dots
#url: "http://blog.huangyz.name/" 
url: "https://lesliekuo.github.io/personal-page-blog/"

# Build settings
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed

moving:
  about_you: Hard work always pays off
  #avatar_url: https://i.loli.net/2019/09/07/wiBh3uMWRUaLX5K.png
  avatar_url: http://m.qpic.cn/psb?/V10NW0g30NUo4i/L.Ipj3u7O4t87B7BS8sk**EyYqlt.5fWrwx8wv15K60!/b/dFIBAAAAAAAA&bo=vALuArwC7gIRCT4!&rf=viewer_4
  date_format: "%b %d"
  back_to: "Index"
  social_links:
    rss: RSS
    github:  huangyz0918
    facebook: huangyz0918
    linkedin: yizheng-huang

